[MPIPreferences]
__clear__ = ["preloads_env_switch"]
_format = "1.0"
abi = "OpenMPI"
binary = "system"
cclibs = []
libmpi = "/common/easybuild/software/OpenMPI/5.0.3-GCC-13.3.0/lib/libmpi"
mpiexec = "mpiexec"
preloads = []
